//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contable.wsaa.afip.gov.ar {
	using System;
	using System.Web.Services;
	using System.Diagnostics;
	using System.Web.Services.Protocols;
	using System.Xml.Serialization;
	using System.ComponentModel;
	
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="LoginCmsSoapBinding", Namespace="https://wsaa.afip.gov.ar/ws/services/LoginCms")]
	public partial class LoginCMSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
		
		/// <remarks/>
		public LoginCMSService() {
			this.Url = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", ResponseNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		[return: System.Xml.Serialization.XmlElementAttribute("loginCmsReturn")]
		public string loginCms(string in0) {
			object[] results = this.Invoke("loginCms", new object[] {
						in0});
			return ((string)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginloginCms(string in0, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("loginCms", new object[] {
						in0}, callback, asyncState);
		}
		
		/// <remarks/>
		public string EndloginCms(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
}
