//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8762
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contable.servicios.pami.org.ar
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", ConfigurationName="Contable.servicios.pami.org.ar.IWebServiceSenasaPortType")]
    public interface IWebServiceSenasaPortType
    {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Contable.servicios.pami.org.ar.saveTransaccionesResponse saveTransacciones(Contable.servicios.pami.org.ar.saveTransacciones request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Contable.servicios.pami.org.ar.getTransaccionesAlertadasResponse getTransaccionesAlertadas(Contable.servicios.pami.org.ar.getTransaccionesAlertadas request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Contable.servicios.pami.org.ar.sendCancelaTransacResponse sendCancelaTransac(Contable.servicios.pami.org.ar.sendCancelaTransac request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Contable.servicios.pami.org.ar.sendAlertaTransaccResponse sendAlertaTransacc(Contable.servicios.pami.org.ar.sendAlertaTransacc request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Contable.servicios.pami.org.ar.sendConfirmaTransaccResponse sendConfirmaTransacc(Contable.servicios.pami.org.ar.sendConfirmaTransacc request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Contable.servicios.pami.org.ar.getTransaccionesResponse getTransacciones(Contable.servicios.pami.org.ar.getTransacciones request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class transaccionSenasaDTO
    {
        
        private string apellidoNombresField;
        
        private string cod_productoField;
        
        private string cuitField;
        
        private string direccionField;
        
        private bool en_transporteField;
        
        private bool en_transporteFieldSpecified;
        
        private string f_elaboracionField;
        
        private string f_operacionField;
        
        private string f_vtoField;
        
        private string gln_destinoField;
        
        private string gln_origenField;
        
        private long id_eventoField;
        
        private bool id_eventoFieldSpecified;
        
        private long id_motivo_destruccionField;
        
        private bool id_motivo_destruccionFieldSpecified;
        
        private long localidadField;
        
        private bool localidadFieldSpecified;
        
        private string motivo_devolucionField;
        
        private string n_caeField;
        
        private string n_caiField;
        
        private decimal n_cantidadField;
        
        private bool n_cantidadFieldSpecified;
        
        private string n_loteField;
        
        private string n_manifiestoField;
        
        private string n_postalField;
        
        private string n_remitoField;
        
        private string n_serieField;
        
        private string n_vale_compraField;
        
        private long numeroField;
        
        private bool numeroFieldSpecified;
        
        private string observacionesField;
        
        private long provinciaField;
        
        private bool provinciaFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoNombres
        {
            get
            {
                return this.apellidoNombresField;
            }
            set
            {
                this.apellidoNombresField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cod_producto
        {
            get
            {
                return this.cod_productoField;
            }
            set
            {
                this.cod_productoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuit
        {
            get
            {
                return this.cuitField;
            }
            set
            {
                this.cuitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool en_transporte
        {
            get
            {
                return this.en_transporteField;
            }
            set
            {
                this.en_transporteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool en_transporteSpecified
        {
            get
            {
                return this.en_transporteFieldSpecified;
            }
            set
            {
                this.en_transporteFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string f_elaboracion
        {
            get
            {
                return this.f_elaboracionField;
            }
            set
            {
                this.f_elaboracionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string f_operacion
        {
            get
            {
                return this.f_operacionField;
            }
            set
            {
                this.f_operacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string f_vto
        {
            get
            {
                return this.f_vtoField;
            }
            set
            {
                this.f_vtoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gln_destino
        {
            get
            {
                return this.gln_destinoField;
            }
            set
            {
                this.gln_destinoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string gln_origen
        {
            get
            {
                return this.gln_origenField;
            }
            set
            {
                this.gln_origenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long id_evento
        {
            get
            {
                return this.id_eventoField;
            }
            set
            {
                this.id_eventoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_eventoSpecified
        {
            get
            {
                return this.id_eventoFieldSpecified;
            }
            set
            {
                this.id_eventoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public long id_motivo_destruccion
        {
            get
            {
                return this.id_motivo_destruccionField;
            }
            set
            {
                this.id_motivo_destruccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_motivo_destruccionSpecified
        {
            get
            {
                return this.id_motivo_destruccionFieldSpecified;
            }
            set
            {
                this.id_motivo_destruccionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public long localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localidadSpecified
        {
            get
            {
                return this.localidadFieldSpecified;
            }
            set
            {
                this.localidadFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string motivo_devolucion
        {
            get
            {
                return this.motivo_devolucionField;
            }
            set
            {
                this.motivo_devolucionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string n_cae
        {
            get
            {
                return this.n_caeField;
            }
            set
            {
                this.n_caeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string n_cai
        {
            get
            {
                return this.n_caiField;
            }
            set
            {
                this.n_caiField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal n_cantidad
        {
            get
            {
                return this.n_cantidadField;
            }
            set
            {
                this.n_cantidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool n_cantidadSpecified
        {
            get
            {
                return this.n_cantidadFieldSpecified;
            }
            set
            {
                this.n_cantidadFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string n_lote
        {
            get
            {
                return this.n_loteField;
            }
            set
            {
                this.n_loteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string n_manifiesto
        {
            get
            {
                return this.n_manifiestoField;
            }
            set
            {
                this.n_manifiestoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string n_postal
        {
            get
            {
                return this.n_postalField;
            }
            set
            {
                this.n_postalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string n_remito
        {
            get
            {
                return this.n_remitoField;
            }
            set
            {
                this.n_remitoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string n_serie
        {
            get
            {
                return this.n_serieField;
            }
            set
            {
                this.n_serieField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string n_vale_compra
        {
            get
            {
                return this.n_vale_compraField;
            }
            set
            {
                this.n_vale_compraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public long numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified
        {
            get
            {
                return this.numeroFieldSpecified;
            }
            set
            {
                this.numeroFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public long provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool provinciaSpecified
        {
            get
            {
                return this.provinciaFieldSpecified;
            }
            set
            {
                this.provinciaFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class confirmacionTransaccionSenasaDTO
    {
        
        private string f_operacionField;
        
        private decimal n_cantidadField;
        
        private bool n_cantidadFieldSpecified;
        
        private long p_ids_transacField;
        
        private bool p_ids_transacFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string f_operacion
        {
            get
            {
                return this.f_operacionField;
            }
            set
            {
                this.f_operacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal n_cantidad
        {
            get
            {
                return this.n_cantidadField;
            }
            set
            {
                this.n_cantidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool n_cantidadSpecified
        {
            get
            {
                return this.n_cantidadFieldSpecified;
            }
            set
            {
                this.n_cantidadFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long p_ids_transac
        {
            get
            {
                return this.p_ids_transacField;
            }
            set
            {
                this.p_ids_transacField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_ids_transacSpecified
        {
            get
            {
                return this.p_ids_transacFieldSpecified;
            }
            set
            {
                this.p_ids_transacFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class transaccionSenasa
    {
        
        private string apellidoNombresField;
        
        private decimal cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private string cod_productoField;
        
        private string cuitField;
        
        private string d_agente_destinoField;
        
        private string d_agente_informadorField;
        
        private string d_agente_origenField;
        
        private string d_envaseField;
        
        private string d_estado_transaccionField;
        
        private string d_eventoField;
        
        private string d_motivo_destruccionField;
        
        private string d_productoField;
        
        private string d_tipo_transaccionField;
        
        private string d_unidadField;
        
        private string direccionField;
        
        private string en_transporteField;
        
        private System.DateTime f_elaboracionField;
        
        private bool f_elaboracionFieldSpecified;
        
        private System.DateTime f_operacionField;
        
        private bool f_operacionFieldSpecified;
        
        private System.DateTime f_transaccionField;
        
        private bool f_transaccionFieldSpecified;
        
        private System.DateTime f_vencimientoField;
        
        private bool f_vencimientoFieldSpecified;
        
        private long id_transaccionField;
        
        private bool id_transaccionFieldSpecified;
        
        private long id_transaccion_globalField;
        
        private bool id_transaccion_globalFieldSpecified;
        
        private string id_unidadField;
        
        private string localidadField;
        
        private string motivo_devolucionField;
        
        private string n_caeField;
        
        private string n_caiField;
        
        private string n_loteField;
        
        private string n_manifiestoField;
        
        private string n_postalField;
        
        private string n_remitoField;
        
        private string n_serieField;
        
        private string n_vale_compraField;
        
        private long numeroField;
        
        private bool numeroFieldSpecified;
        
        private string observacionesField;
        
        private string provinciaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoNombres
        {
            get
            {
                return this.apellidoNombresField;
            }
            set
            {
                this.apellidoNombresField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified
        {
            get
            {
                return this.cantidadFieldSpecified;
            }
            set
            {
                this.cantidadFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cod_producto
        {
            get
            {
                return this.cod_productoField;
            }
            set
            {
                this.cod_productoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cuit
        {
            get
            {
                return this.cuitField;
            }
            set
            {
                this.cuitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string d_agente_destino
        {
            get
            {
                return this.d_agente_destinoField;
            }
            set
            {
                this.d_agente_destinoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string d_agente_informador
        {
            get
            {
                return this.d_agente_informadorField;
            }
            set
            {
                this.d_agente_informadorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string d_agente_origen
        {
            get
            {
                return this.d_agente_origenField;
            }
            set
            {
                this.d_agente_origenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string d_envase
        {
            get
            {
                return this.d_envaseField;
            }
            set
            {
                this.d_envaseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string d_estado_transaccion
        {
            get
            {
                return this.d_estado_transaccionField;
            }
            set
            {
                this.d_estado_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string d_evento
        {
            get
            {
                return this.d_eventoField;
            }
            set
            {
                this.d_eventoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string d_motivo_destruccion
        {
            get
            {
                return this.d_motivo_destruccionField;
            }
            set
            {
                this.d_motivo_destruccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string d_producto
        {
            get
            {
                return this.d_productoField;
            }
            set
            {
                this.d_productoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string d_tipo_transaccion
        {
            get
            {
                return this.d_tipo_transaccionField;
            }
            set
            {
                this.d_tipo_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string d_unidad
        {
            get
            {
                return this.d_unidadField;
            }
            set
            {
                this.d_unidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string en_transporte
        {
            get
            {
                return this.en_transporteField;
            }
            set
            {
                this.en_transporteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime f_elaboracion
        {
            get
            {
                return this.f_elaboracionField;
            }
            set
            {
                this.f_elaboracionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool f_elaboracionSpecified
        {
            get
            {
                return this.f_elaboracionFieldSpecified;
            }
            set
            {
                this.f_elaboracionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public System.DateTime f_operacion
        {
            get
            {
                return this.f_operacionField;
            }
            set
            {
                this.f_operacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool f_operacionSpecified
        {
            get
            {
                return this.f_operacionFieldSpecified;
            }
            set
            {
                this.f_operacionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public System.DateTime f_transaccion
        {
            get
            {
                return this.f_transaccionField;
            }
            set
            {
                this.f_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool f_transaccionSpecified
        {
            get
            {
                return this.f_transaccionFieldSpecified;
            }
            set
            {
                this.f_transaccionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public System.DateTime f_vencimiento
        {
            get
            {
                return this.f_vencimientoField;
            }
            set
            {
                this.f_vencimientoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool f_vencimientoSpecified
        {
            get
            {
                return this.f_vencimientoFieldSpecified;
            }
            set
            {
                this.f_vencimientoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public long id_transaccion
        {
            get
            {
                return this.id_transaccionField;
            }
            set
            {
                this.id_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_transaccionSpecified
        {
            get
            {
                return this.id_transaccionFieldSpecified;
            }
            set
            {
                this.id_transaccionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public long id_transaccion_global
        {
            get
            {
                return this.id_transaccion_globalField;
            }
            set
            {
                this.id_transaccion_globalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_transaccion_globalSpecified
        {
            get
            {
                return this.id_transaccion_globalFieldSpecified;
            }
            set
            {
                this.id_transaccion_globalFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string id_unidad
        {
            get
            {
                return this.id_unidadField;
            }
            set
            {
                this.id_unidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string motivo_devolucion
        {
            get
            {
                return this.motivo_devolucionField;
            }
            set
            {
                this.motivo_devolucionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string n_cae
        {
            get
            {
                return this.n_caeField;
            }
            set
            {
                this.n_caeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string n_cai
        {
            get
            {
                return this.n_caiField;
            }
            set
            {
                this.n_caiField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string n_lote
        {
            get
            {
                return this.n_loteField;
            }
            set
            {
                this.n_loteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string n_manifiesto
        {
            get
            {
                return this.n_manifiestoField;
            }
            set
            {
                this.n_manifiestoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string n_postal
        {
            get
            {
                return this.n_postalField;
            }
            set
            {
                this.n_postalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string n_remito
        {
            get
            {
                return this.n_remitoField;
            }
            set
            {
                this.n_remitoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string n_serie
        {
            get
            {
                return this.n_serieField;
            }
            set
            {
                this.n_serieField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string n_vale_compra
        {
            get
            {
                return this.n_vale_compraField;
            }
            set
            {
                this.n_vale_compraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public long numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified
        {
            get
            {
                return this.numeroFieldSpecified;
            }
            set
            {
                this.numeroFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class webServiceError
    {
        
        private string c_errorField;
        
        private string d_errorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string c_error
        {
            get
            {
                return this.c_errorField;
            }
            set
            {
                this.c_errorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string d_error
        {
            get
            {
                return this.d_errorField;
            }
            set
            {
                this.d_errorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resultadoTransaccionSenasaWS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resultadoTransaccionSenasaPaginadoWS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class webServiceResult
    {
        
        private string codigoTransaccionField;
        
        private webServiceError[] erroresField;
        
        private bool resultadoField;
        
        private bool resultadoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoTransaccion
        {
            get
            {
                return this.codigoTransaccionField;
            }
            set
            {
                this.codigoTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("errores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public webServiceError[] errores
        {
            get
            {
                return this.erroresField;
            }
            set
            {
                this.erroresField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultadoSpecified
        {
            get
            {
                return this.resultadoFieldSpecified;
            }
            set
            {
                this.resultadoFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resultadoTransaccionSenasaPaginadoWS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class resultadoTransaccionSenasaWS : webServiceResult
    {
        
        private transaccionSenasa[] listField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public transaccionSenasa[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/")]
    public partial class resultadoTransaccionSenasaPaginadoWS : resultadoTransaccionSenasaWS
    {
        
        private long cantPaginasField;
        
        private bool cantPaginasFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long cantPaginas
        {
            get
            {
                return this.cantPaginasField;
            }
            set
            {
                this.cantPaginasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantPaginasSpecified
        {
            get
            {
                return this.cantPaginasFieldSpecified;
            }
            set
            {
                this.cantPaginasFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveTransacciones", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class saveTransacciones
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transaccionSenasaDTO[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public saveTransacciones()
        {
        }
        
        public saveTransacciones(transaccionSenasaDTO[] arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveTransaccionesResponse", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class saveTransaccionesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Contable.servicios.pami.org.ar.webServiceResult @return;
        
        public saveTransaccionesResponse()
        {
        }
        
        public saveTransaccionesResponse(Contable.servicios.pami.org.ar.webServiceResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransaccionesAlertadas", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class getTransaccionesAlertadas
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg11;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg12;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg13;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg14;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg15;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg16;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg17;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg18;
        
        public getTransaccionesAlertadas()
        {
        }
        
        public getTransaccionesAlertadas(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15, 
                    string arg16, 
                    long arg17, 
                    long arg18)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
            this.arg10 = arg10;
            this.arg11 = arg11;
            this.arg12 = arg12;
            this.arg13 = arg13;
            this.arg14 = arg14;
            this.arg15 = arg15;
            this.arg16 = arg16;
            this.arg17 = arg17;
            this.arg18 = arg18;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransaccionesAlertadasResponse", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class getTransaccionesAlertadasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Contable.servicios.pami.org.ar.resultadoTransaccionSenasaPaginadoWS @return;
        
        public getTransaccionesAlertadasResponse()
        {
        }
        
        public getTransaccionesAlertadasResponse(Contable.servicios.pami.org.ar.resultadoTransaccionSenasaPaginadoWS @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCancelaTransac", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class sendCancelaTransac
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public sendCancelaTransac()
        {
        }
        
        public sendCancelaTransac(long arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCancelaTransacResponse", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class sendCancelaTransacResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Contable.servicios.pami.org.ar.webServiceResult @return;
        
        public sendCancelaTransacResponse()
        {
        }
        
        public sendCancelaTransacResponse(Contable.servicios.pami.org.ar.webServiceResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendAlertaTransacc", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class sendAlertaTransacc
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] arg2;
        
        public sendAlertaTransacc()
        {
        }
        
        public sendAlertaTransacc(string arg0, string arg1, long[] arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendAlertaTransaccResponse", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class sendAlertaTransaccResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Contable.servicios.pami.org.ar.webServiceResult @return;
        
        public sendAlertaTransaccResponse()
        {
        }
        
        public sendAlertaTransaccResponse(Contable.servicios.pami.org.ar.webServiceResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendConfirmaTransacc", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class sendConfirmaTransacc
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public confirmacionTransaccionSenasaDTO[] arg2;
        
        public sendConfirmaTransacc()
        {
        }
        
        public sendConfirmaTransacc(string arg0, string arg1, confirmacionTransaccionSenasaDTO[] arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendConfirmaTransaccResponse", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class sendConfirmaTransaccResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Contable.servicios.pami.org.ar.webServiceResult @return;
        
        public sendConfirmaTransaccResponse()
        {
        }
        
        public sendConfirmaTransaccResponse(Contable.servicios.pami.org.ar.webServiceResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransacciones", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class getTransacciones
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg11;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg12;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg13;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg14;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg15;
        
        public getTransacciones()
        {
        }
        
        public getTransacciones(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
            this.arg10 = arg10;
            this.arg11 = arg11;
            this.arg12 = arg12;
            this.arg13 = arg13;
            this.arg14 = arg14;
            this.arg15 = arg15;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransaccionesResponse", WrapperNamespace="http://business.WebServiceSenasa.inssjp.com/", IsWrapped=true)]
    public partial class getTransaccionesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://business.WebServiceSenasa.inssjp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Contable.servicios.pami.org.ar.resultadoTransaccionSenasaPaginadoWS @return;
        
        public getTransaccionesResponse()
        {
        }
        
        public getTransaccionesResponse(Contable.servicios.pami.org.ar.resultadoTransaccionSenasaPaginadoWS @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWebServiceSenasaPortTypeChannel : Contable.servicios.pami.org.ar.IWebServiceSenasaPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebServiceSenasaPortTypeClient : System.ServiceModel.ClientBase<Contable.servicios.pami.org.ar.IWebServiceSenasaPortType>, Contable.servicios.pami.org.ar.IWebServiceSenasaPortType
    {
        
        public WebServiceSenasaPortTypeClient()
        {
        }
        
        public WebServiceSenasaPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WebServiceSenasaPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WebServiceSenasaPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WebServiceSenasaPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contable.servicios.pami.org.ar.saveTransaccionesResponse Contable.servicios.pami.org.ar.IWebServiceSenasaPortType.saveTransacciones(Contable.servicios.pami.org.ar.saveTransacciones request)
        {
            return base.Channel.saveTransacciones(request);
        }
        
        public Contable.servicios.pami.org.ar.webServiceResult saveTransacciones(transaccionSenasaDTO[] arg0, string arg1, string arg2)
        {
            Contable.servicios.pami.org.ar.saveTransacciones inValue = new Contable.servicios.pami.org.ar.saveTransacciones();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Contable.servicios.pami.org.ar.saveTransaccionesResponse retVal = ((Contable.servicios.pami.org.ar.IWebServiceSenasaPortType)(this)).saveTransacciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contable.servicios.pami.org.ar.getTransaccionesAlertadasResponse Contable.servicios.pami.org.ar.IWebServiceSenasaPortType.getTransaccionesAlertadas(Contable.servicios.pami.org.ar.getTransaccionesAlertadas request)
        {
            return base.Channel.getTransaccionesAlertadas(request);
        }
        
        public Contable.servicios.pami.org.ar.resultadoTransaccionSenasaPaginadoWS getTransaccionesAlertadas(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15, 
                    string arg16, 
                    long arg17, 
                    long arg18)
        {
            Contable.servicios.pami.org.ar.getTransaccionesAlertadas inValue = new Contable.servicios.pami.org.ar.getTransaccionesAlertadas();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            inValue.arg10 = arg10;
            inValue.arg11 = arg11;
            inValue.arg12 = arg12;
            inValue.arg13 = arg13;
            inValue.arg14 = arg14;
            inValue.arg15 = arg15;
            inValue.arg16 = arg16;
            inValue.arg17 = arg17;
            inValue.arg18 = arg18;
            Contable.servicios.pami.org.ar.getTransaccionesAlertadasResponse retVal = ((Contable.servicios.pami.org.ar.IWebServiceSenasaPortType)(this)).getTransaccionesAlertadas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contable.servicios.pami.org.ar.sendCancelaTransacResponse Contable.servicios.pami.org.ar.IWebServiceSenasaPortType.sendCancelaTransac(Contable.servicios.pami.org.ar.sendCancelaTransac request)
        {
            return base.Channel.sendCancelaTransac(request);
        }
        
        public Contable.servicios.pami.org.ar.webServiceResult sendCancelaTransac(long arg0, string arg1, string arg2)
        {
            Contable.servicios.pami.org.ar.sendCancelaTransac inValue = new Contable.servicios.pami.org.ar.sendCancelaTransac();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Contable.servicios.pami.org.ar.sendCancelaTransacResponse retVal = ((Contable.servicios.pami.org.ar.IWebServiceSenasaPortType)(this)).sendCancelaTransac(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contable.servicios.pami.org.ar.sendAlertaTransaccResponse Contable.servicios.pami.org.ar.IWebServiceSenasaPortType.sendAlertaTransacc(Contable.servicios.pami.org.ar.sendAlertaTransacc request)
        {
            return base.Channel.sendAlertaTransacc(request);
        }
        
        public Contable.servicios.pami.org.ar.webServiceResult sendAlertaTransacc(string arg0, string arg1, long[] arg2)
        {
            Contable.servicios.pami.org.ar.sendAlertaTransacc inValue = new Contable.servicios.pami.org.ar.sendAlertaTransacc();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Contable.servicios.pami.org.ar.sendAlertaTransaccResponse retVal = ((Contable.servicios.pami.org.ar.IWebServiceSenasaPortType)(this)).sendAlertaTransacc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contable.servicios.pami.org.ar.sendConfirmaTransaccResponse Contable.servicios.pami.org.ar.IWebServiceSenasaPortType.sendConfirmaTransacc(Contable.servicios.pami.org.ar.sendConfirmaTransacc request)
        {
            return base.Channel.sendConfirmaTransacc(request);
        }
        
        public Contable.servicios.pami.org.ar.webServiceResult sendConfirmaTransacc(string arg0, string arg1, confirmacionTransaccionSenasaDTO[] arg2)
        {
            Contable.servicios.pami.org.ar.sendConfirmaTransacc inValue = new Contable.servicios.pami.org.ar.sendConfirmaTransacc();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Contable.servicios.pami.org.ar.sendConfirmaTransaccResponse retVal = ((Contable.servicios.pami.org.ar.IWebServiceSenasaPortType)(this)).sendConfirmaTransacc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contable.servicios.pami.org.ar.getTransaccionesResponse Contable.servicios.pami.org.ar.IWebServiceSenasaPortType.getTransacciones(Contable.servicios.pami.org.ar.getTransacciones request)
        {
            return base.Channel.getTransacciones(request);
        }
        
        public Contable.servicios.pami.org.ar.resultadoTransaccionSenasaPaginadoWS getTransacciones(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15)
        {
            Contable.servicios.pami.org.ar.getTransacciones inValue = new Contable.servicios.pami.org.ar.getTransacciones();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            inValue.arg10 = arg10;
            inValue.arg11 = arg11;
            inValue.arg12 = arg12;
            inValue.arg13 = arg13;
            inValue.arg14 = arg14;
            inValue.arg15 = arg15;
            Contable.servicios.pami.org.ar.getTransaccionesResponse retVal = ((Contable.servicios.pami.org.ar.IWebServiceSenasaPortType)(this)).getTransacciones(inValue);
            return retVal.@return;
        }
    }
}
