//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contable.servicios1.afip.gov.ar {
	using System;
	using System.Web.Services;
	using System.Diagnostics;
	using System.Web.Services.Protocols;
	using System.Xml.Serialization;
	using System.ComponentModel;
	
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://ar.gov.afip.dif.FEV1/")]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FEDetResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECabResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FEDetRequest))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECabRequest))]
	public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
		
		/// <remarks/>
		public Service() {
			this.Url = "https://servicios1.afip.gov.ar/wsfev1/service.asmx";
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAESolicitar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECAEResponse FECAESolicitar(FEAuthRequest Auth, FECAERequest FeCAEReq) {
			object[] results = this.Invoke("FECAESolicitar", new object[] {
						Auth,
						FeCAEReq});
			return ((FECAEResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECAESolicitar(FEAuthRequest Auth, FECAERequest FeCAEReq, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECAESolicitar", new object[] {
						Auth,
						FeCAEReq}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECAEResponse EndFECAESolicitar(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECAEResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECompTotXRequest", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FERegXReqResponse FECompTotXRequest(FEAuthRequest Auth) {
			object[] results = this.Invoke("FECompTotXRequest", new object[] {
						Auth});
			return ((FERegXReqResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECompTotXRequest(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECompTotXRequest", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public FERegXReqResponse EndFECompTotXRequest(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FERegXReqResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEDummy", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public DummyResponse FEDummy() {
			object[] results = this.Invoke("FEDummy", new object[0]);
			return ((DummyResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEDummy(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEDummy", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public DummyResponse EndFEDummy(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((DummyResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FERecuperaLastCbteResponse FECompUltimoAutorizado(FEAuthRequest Auth, int PtoVta, int CbteTipo) {
			object[] results = this.Invoke("FECompUltimoAutorizado", new object[] {
						Auth,
						PtoVta,
						CbteTipo});
			return ((FERecuperaLastCbteResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECompUltimoAutorizado(FEAuthRequest Auth, int PtoVta, int CbteTipo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECompUltimoAutorizado", new object[] {
						Auth,
						PtoVta,
						CbteTipo}, callback, asyncState);
		}
		
		/// <remarks/>
		public FERecuperaLastCbteResponse EndFECompUltimoAutorizado(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FERecuperaLastCbteResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECompConsultar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECompConsultaResponse FECompConsultar(FEAuthRequest Auth, FECompConsultaReq FeCompConsReq) {
			object[] results = this.Invoke("FECompConsultar", new object[] {
						Auth,
						FeCompConsReq});
			return ((FECompConsultaResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECompConsultar(FEAuthRequest Auth, FECompConsultaReq FeCompConsReq, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECompConsultar", new object[] {
						Auth,
						FeCompConsReq}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECompConsultaResponse EndFECompConsultar(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECompConsultaResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEARegInformativo", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECAEAResponse FECAEARegInformativo(FEAuthRequest Auth, FECAEARequest FeCAEARegInfReq) {
			object[] results = this.Invoke("FECAEARegInformativo", new object[] {
						Auth,
						FeCAEARegInfReq});
			return ((FECAEAResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECAEARegInformativo(FEAuthRequest Auth, FECAEARequest FeCAEARegInfReq, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECAEARegInformativo", new object[] {
						Auth,
						FeCAEARegInfReq}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECAEAResponse EndFECAEARegInformativo(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECAEAResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEASolicitar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECAEAGetResponse FECAEASolicitar(FEAuthRequest Auth, int Periodo, short Orden) {
			object[] results = this.Invoke("FECAEASolicitar", new object[] {
						Auth,
						Periodo,
						Orden});
			return ((FECAEAGetResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECAEASolicitar(FEAuthRequest Auth, int Periodo, short Orden, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECAEASolicitar", new object[] {
						Auth,
						Periodo,
						Orden}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECAEAGetResponse EndFECAEASolicitar(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECAEAGetResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECAEASinMovConsResponse FECAEASinMovimientoConsultar(FEAuthRequest Auth, string CAEA, int PtoVta) {
			object[] results = this.Invoke("FECAEASinMovimientoConsultar", new object[] {
						Auth,
						CAEA,
						PtoVta});
			return ((FECAEASinMovConsResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECAEASinMovimientoConsultar(FEAuthRequest Auth, string CAEA, int PtoVta, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECAEASinMovimientoConsultar", new object[] {
						Auth,
						CAEA,
						PtoVta}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECAEASinMovConsResponse EndFECAEASinMovimientoConsultar(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECAEASinMovConsResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECAEASinMovResponse FECAEASinMovimientoInformar(FEAuthRequest Auth, int PtoVta, string CAEA) {
			object[] results = this.Invoke("FECAEASinMovimientoInformar", new object[] {
						Auth,
						PtoVta,
						CAEA});
			return ((FECAEASinMovResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECAEASinMovimientoInformar(FEAuthRequest Auth, int PtoVta, string CAEA, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECAEASinMovimientoInformar", new object[] {
						Auth,
						PtoVta,
						CAEA}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECAEASinMovResponse EndFECAEASinMovimientoInformar(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECAEASinMovResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FECAEAConsultar", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECAEAGetResponse FECAEAConsultar(FEAuthRequest Auth, int Periodo, short Orden) {
			object[] results = this.Invoke("FECAEAConsultar", new object[] {
						Auth,
						Periodo,
						Orden});
			return ((FECAEAGetResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFECAEAConsultar(FEAuthRequest Auth, int Periodo, short Orden, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FECAEAConsultar", new object[] {
						Auth,
						Periodo,
						Orden}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECAEAGetResponse EndFECAEAConsultar(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECAEAGetResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FECotizacionResponse FEParamGetCotizacion(FEAuthRequest Auth, string MonId) {
			object[] results = this.Invoke("FEParamGetCotizacion", new object[] {
						Auth,
						MonId});
			return ((FECotizacionResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetCotizacion(FEAuthRequest Auth, string MonId, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetCotizacion", new object[] {
						Auth,
						MonId}, callback, asyncState);
		}
		
		/// <remarks/>
		public FECotizacionResponse EndFEParamGetCotizacion(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FECotizacionResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FETributoResponse FEParamGetTiposTributos(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposTributos", new object[] {
						Auth});
			return ((FETributoResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposTributos(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposTributos", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public FETributoResponse EndFEParamGetTiposTributos(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FETributoResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public MonedaResponse FEParamGetTiposMonedas(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposMonedas", new object[] {
						Auth});
			return ((MonedaResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposMonedas(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposMonedas", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public MonedaResponse EndFEParamGetTiposMonedas(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((MonedaResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IvaTipoResponse FEParamGetTiposIva(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposIva", new object[] {
						Auth});
			return ((IvaTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposIva(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposIva", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public IvaTipoResponse EndFEParamGetTiposIva(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((IvaTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public OpcionalTipoResponse FEParamGetTiposOpcional(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposOpcional", new object[] {
						Auth});
			return ((OpcionalTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposOpcional(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposOpcional", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public OpcionalTipoResponse EndFEParamGetTiposOpcional(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((OpcionalTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public ConceptoTipoResponse FEParamGetTiposConcepto(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposConcepto", new object[] {
						Auth});
			return ((ConceptoTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposConcepto(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposConcepto", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public ConceptoTipoResponse EndFEParamGetTiposConcepto(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((ConceptoTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FEPtoVentaResponse FEParamGetPtosVenta(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetPtosVenta", new object[] {
						Auth});
			return ((FEPtoVentaResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetPtosVenta(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetPtosVenta", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public FEPtoVentaResponse EndFEParamGetPtosVenta(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FEPtoVentaResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public CbteTipoResponse FEParamGetTiposCbte(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposCbte", new object[] {
						Auth});
			return ((CbteTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposCbte(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposCbte", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public CbteTipoResponse EndFEParamGetTiposCbte(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((CbteTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public DocTipoResponse FEParamGetTiposDoc(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposDoc", new object[] {
						Auth});
			return ((DocTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposDoc(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposDoc", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public DocTipoResponse EndFEParamGetTiposDoc(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((DocTipoResponse)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises", RequestNamespace="http://ar.gov.afip.dif.FEV1/", ResponseNamespace="http://ar.gov.afip.dif.FEV1/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FEPaisResponse FEParamGetTiposPaises(FEAuthRequest Auth) {
			object[] results = this.Invoke("FEParamGetTiposPaises", new object[] {
						Auth});
			return ((FEPaisResponse)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginFEParamGetTiposPaises(FEAuthRequest Auth, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("FEParamGetTiposPaises", new object[] {
						Auth}, callback, asyncState);
		}
		
		/// <remarks/>
		public FEPaisResponse EndFEParamGetTiposPaises(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((FEPaisResponse)(results[0]));
		}
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FEAuthRequest {
		
		/// <comentarios/>
		public string Token;
		
		/// <comentarios/>
		public string Sign;
		
		/// <comentarios/>
		public long Cuit;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class PaisTipo {
		
		/// <comentarios/>
		public short Id;
		
		/// <comentarios/>
		public string Desc;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FEPaisResponse {
		
		/// <comentarios/>
		public PaisTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Err {
		
		/// <comentarios/>
		public int Code;
		
		/// <comentarios/>
		public string Msg;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Evt {
		
		/// <comentarios/>
		public int Code;
		
		/// <comentarios/>
		public string Msg;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class DocTipo {
		
		/// <comentarios/>
		public int Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class DocTipoResponse {
		
		/// <comentarios/>
		public DocTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class CbteTipo {
		
		/// <comentarios/>
		public int Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class CbteTipoResponse {
		
		/// <comentarios/>
		public CbteTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class PtoVenta {
		
		/// <comentarios/>
		public short Nro;
		
		/// <comentarios/>
		public string EmisionTipo;
		
		/// <comentarios/>
		public string Bloqueado;
		
		/// <comentarios/>
		public string FchBaja;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FEPtoVentaResponse {
		
		/// <comentarios/>
		public PtoVenta[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class ConceptoTipo {
		
		/// <comentarios/>
		public int Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class ConceptoTipoResponse {
		
		/// <comentarios/>
		public ConceptoTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class OpcionalTipo {
		
		/// <comentarios/>
		public string Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class OpcionalTipoResponse {
		
		/// <comentarios/>
		public OpcionalTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class IvaTipo {
		
		/// <comentarios/>
		public string Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class IvaTipoResponse {
		
		/// <comentarios/>
		public IvaTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Moneda {
		
		/// <comentarios/>
		public string Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class MonedaResponse {
		
		/// <comentarios/>
		public Moneda[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class TributoTipo {
		
		/// <comentarios/>
		public short Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public string FchDesde;
		
		/// <comentarios/>
		public string FchHasta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FETributoResponse {
		
		/// <comentarios/>
		public TributoTipo[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Cotizacion {
		
		/// <comentarios/>
		public string MonId;
		
		/// <comentarios/>
		public double MonCotiz;
		
		/// <comentarios/>
		public string FchCotiz;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECotizacionResponse {
		
		/// <comentarios/>
		public Cotizacion ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEASinMovResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEASinMov {
		
		/// <comentarios/>
		public string CAEA;
		
		/// <comentarios/>
		public string FchProceso;
		
		/// <comentarios/>
		public int PtoVta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEASinMovResponse : FECAEASinMov {
		
		/// <comentarios/>
		public string Resultado;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEASinMovConsResponse {
		
		/// <comentarios/>
		public FECAEASinMov[] ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEAGet {
		
		/// <comentarios/>
		public string CAEA;
		
		/// <comentarios/>
		public int Periodo;
		
		/// <comentarios/>
		public short Orden;
		
		/// <comentarios/>
		public string FchVigDesde;
		
		/// <comentarios/>
		public string FchVigHasta;
		
		/// <comentarios/>
		public string FchTopeInf;
		
		/// <comentarios/>
		public string FchProceso;
		
		/// <comentarios/>
		public Obs[] Observaciones;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Obs {
		
		/// <comentarios/>
		public int Code;
		
		/// <comentarios/>
		public string Msg;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEAGetResponse {
		
		/// <comentarios/>
		public FECAEAGet ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEAResponse {
		
		/// <comentarios/>
		public FECAEACabResponse FeCabResp;
		
		/// <comentarios/>
		public FECAEADetResponse[] FeDetResp;
		
		/// <comentarios/>
		public Evt[] Events;
		
		/// <comentarios/>
		public Err[] Errors;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEACabResponse : FECabResponse {
	}
	
	/// <comentarios/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEACabResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAECabResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECabResponse {
		
		/// <comentarios/>
		public long Cuit;
		
		/// <comentarios/>
		public int PtoVta;
		
		/// <comentarios/>
		public int CbteTipo;
		
		/// <comentarios/>
		public string FchProceso;
		
		/// <comentarios/>
		public int CantReg;
		
		/// <comentarios/>
		public string Resultado;
		
		/// <comentarios/>
		public string Reproceso;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAECabResponse : FECabResponse {
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEADetResponse : FEDetResponse {
		
		/// <comentarios/>
		public string CAEA;
	}
	
	/// <comentarios/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEADetResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEDetResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FEDetResponse {
		
		/// <comentarios/>
		public int Concepto;
		
		/// <comentarios/>
		public int DocTipo;
		
		/// <comentarios/>
		public long DocNro;
		
		/// <comentarios/>
		public long CbteDesde;
		
		/// <comentarios/>
		public long CbteHasta;
		
		/// <comentarios/>
		public string CbteFch;
		
		/// <comentarios/>
		public string Resultado;
		
		/// <comentarios/>
		public Obs[] Observaciones;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEDetResponse : FEDetResponse {
		
		/// <comentarios/>
		public string CAE;
		
		/// <comentarios/>
		public string CAEFchVto;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEARequest {
		
		/// <comentarios/>
		public FECAEACabRequest FeCabReq;
		
		/// <comentarios/>
		public FECAEADetRequest[] FeDetReq;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEACabRequest : FECabRequest {
	}
	
	/// <comentarios/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEACabRequest))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAECabRequest))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECabRequest {
		
		/// <comentarios/>
		public int CantReg;
		
		/// <comentarios/>
		public int PtoVta;
		
		/// <comentarios/>
		public int CbteTipo;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAECabRequest : FECabRequest {
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEADetRequest : FEDetRequest {
		
		/// <comentarios/>
		public string CAEA;
	}
	
	/// <comentarios/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEADetRequest))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECAEDetRequest))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECompConsResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FEDetRequest {
		
		/// <comentarios/>
		public int Concepto;
		
		/// <comentarios/>
		public int DocTipo;
		
		/// <comentarios/>
		public long DocNro;
		
		/// <comentarios/>
		public long CbteDesde;
		
		/// <comentarios/>
		public long CbteHasta;
		
		/// <comentarios/>
		public string CbteFch;
		
		/// <comentarios/>
		public double ImpTotal;
		
		/// <comentarios/>
		public double ImpTotConc;
		
		/// <comentarios/>
		public double ImpNeto;
		
		/// <comentarios/>
		public double ImpOpEx;
		
		/// <comentarios/>
		public double ImpTrib;
		
		/// <comentarios/>
		public double ImpIVA;
		
		/// <comentarios/>
		public string FchServDesde;
		
		/// <comentarios/>
		public string FchServHasta;
		
		/// <comentarios/>
		public string FchVtoPago;
		
		/// <comentarios/>
		public string MonId;
		
		/// <comentarios/>
		public double MonCotiz;
		
		/// <comentarios/>
		public CbteAsoc[] CbtesAsoc;
		
		/// <comentarios/>
		public Tributo[] Tributos;
		
		/// <comentarios/>
		public AlicIva[] Iva;
		
		/// <comentarios/>
		public Opcional[] Opcionales;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class CbteAsoc {
		
		/// <comentarios/>
		public int Tipo;
		
		/// <comentarios/>
		public int PtoVta;
		
		/// <comentarios/>
		public long Nro;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Tributo {
		
		/// <comentarios/>
		public short Id;
		
		/// <comentarios/>
		public string Desc;
		
		/// <comentarios/>
		public double BaseImp;
		
		/// <comentarios/>
		public double Alic;
		
		/// <comentarios/>
		public double Importe;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class AlicIva {
		
		/// <comentarios/>
		public int Id;
		
		/// <comentarios/>
		public double BaseImp;
		
		/// <comentarios/>
		public double Importe;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class Opcional {
		
		/// <comentarios/>
		public string Id;
		
		/// <comentarios/>
		public string Valor;
	}
	
	/// <comentarios/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FECompConsResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEDetRequest : FEDetRequest {
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECompConsResponse : FECAEDetRequest {
		
		/// <comentarios/>
		public string Resultado;
		
		/// <comentarios/>
		public string CodAutorizacion;
		
		/// <comentarios/>
		public string EmisionTipo;
		
		/// <comentarios/>
		public string FchVto;
		
		/// <comentarios/>
		public string FchProceso;
		
		/// <comentarios/>
		public Obs[] Observaciones;
		
		/// <comentarios/>
		public int PtoVta;
		
		/// <comentarios/>
		public int CbteTipo;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECompConsultaResponse {
		
		/// <comentarios/>
		public FECompConsResponse ResultGet;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECompConsultaReq {
		
		/// <comentarios/>
		public int CbteTipo;
		
		/// <comentarios/>
		public long CbteNro;
		
		/// <comentarios/>
		public int PtoVta;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FERecuperaLastCbteResponse {
		
		/// <comentarios/>
		public int PtoVta;
		
		/// <comentarios/>
		public int CbteTipo;
		
		/// <comentarios/>
		public int CbteNro;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class DummyResponse {
		
		/// <comentarios/>
		public string AppServer;
		
		/// <comentarios/>
		public string DbServer;
		
		/// <comentarios/>
		public string AuthServer;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FERegXReqResponse {
		
		/// <comentarios/>
		public int RegXReq;
		
		/// <comentarios/>
		public Err[] Errors;
		
		/// <comentarios/>
		public Evt[] Events;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAEResponse {
		
		/// <comentarios/>
		public FECAECabResponse FeCabResp;
		
		/// <comentarios/>
		public FECAEDetResponse[] FeDetResp;
		
		/// <comentarios/>
		public Evt[] Events;
		
		/// <comentarios/>
		public Err[] Errors;
	}
	
	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.4936-Beta-3ea20cfa")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.FEV1/")]
	public partial class FECAERequest {
		
		/// <comentarios/>
		public FECAECabRequest FeCabReq;
		
		/// <comentarios/>
		public FECAEDetRequest[] FeDetReq;
	}
}
